application: skabb-radio
version: 3
runtime: python
api_version: 1



handlers:
- url: /static
  static_dir: static
#- url: /oneoff
#  script: src/oneoff.py
- url: /feed/.*
  script: src/feed.py
- url: /json/.*
  script: src/main.py
#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin
- url: /
  static_files: static/index.html
  upload: static/(.*\.(html))
- url: .*
  static_dir: static
  
  
builtins:
  - datastore_admin: on
#  - remote_api: on